workflows:
  ios-workflow:
    name: iOS Build for Capacitor
    environment:
      node: 18.16.0   # versión de Node.js
      npm: 9.5.1
      xcode: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build React app
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Build iOS app
        script: xcodebuild -workspace ios/App/App.xcworkspace -scheme App -sdk iphonesimulator -configuration Debug build
    artifacts:
      - build/ios/Debug-iphonesimulator/*.app
    publishing:
      email:
        recipients:
          - viyago.app@gmail.com
