workflows:
  ios-simulator-capacitor:
    name: iOS Simulator build (Capacitor + Vite → App.zip for Appetize)
    environment:
      node: 20.11.0   # ✅ Node 20 requerido por Capacitor
      npm: 10.2.4
      xcode: 15.0
    cache:
      cache_paths:
        - ~/.npm
    scripts:
      - name: Install dependencies (clean)
        script: npm ci || npm install

      - name: Build React app
        script: npm run build   # ✅ genera dist/ automáticamente

      - name: Add iOS platform (if not present)
        script: npx cap add ios || true

      - name: Sync Capacitor (copy web to iOS)
        script: npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install

      - name: Xcode build for Simulator (Debug)
        script: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath ios_build

      - name: Package .app for Appetize
        script: |
          cd ios_build/Build/Products/Debug-iphonesimulator
          zip -r VitaGo-sim.zip App.app   # ✅ Appetize acepta este .zip
    artifacts:
      - ios_build/Build/Products/Debug-iphonesimulator/VitaGo-sim.zip

    publishing:
      email:
        recipients:
          - vitago.app@gmail.com

